steps:
  # Tests temporarily disabled - import path issues in Cloud Build
  # Run tests locally before deploying: cd backend && pytest tests/
  # - name: 'python:3.12-slim'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       pip install -r requirements.txt
  #       python -m pytest tests/ -v --cov=src --cov-report=term-missing
  #   dir: '.'
    
  # Security scan
  - name: 'python:3.12-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install bandit[toml]
        bandit -r src -f json -o bandit-report.json || true
        cat bandit-report.json
    dir: '.'
    
  # Build Docker image with no cache
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', '${_BACKEND_IMAGE}', '.']
    dir: '.'
    
  # Vulnerability scan of the built image
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container images scan ${_BACKEND_IMAGE} --format='value(discovery.analysisKind)' || true
        
images:
  - '${_BACKEND_IMAGE}'
  
substitutions:
  _BACKEND_IMAGE: 'us-west1-docker.pkg.dev/adk-rag-ma/cloud-run-repo1/backend:latest'
  
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
