"""
Configuration settings for the RAG Agent - USFS Account
Account: usfs
Project: usfs-gcp-arch-testing
Region: us-east4

Generated by deploy_env_config.py on 2026-02-25 00:47:02
DO NOT EDIT MANUALLY — regenerate with:
  python backend/deploy_env_config.py --env environments/usfs.yaml
"""

import os

# Account identifier
ACCOUNT_NAME = "usfs"
ACCOUNT_DESCRIPTION = "Usfs Account"

# Vertex AI settings
PROJECT_ID = os.environ.get("PROJECT_ID", "usfs-gcp-arch-testing")
LOCATION = os.environ.get("GOOGLE_CLOUD_LOCATION", "us-east4")

# RAG settings
DEFAULT_CHUNK_SIZE = 512
DEFAULT_CHUNK_OVERLAP = 100
DEFAULT_TOP_K = 5
DEFAULT_DISTANCE_THRESHOLD = 0.5
DEFAULT_EMBEDDING_MODEL = "publishers/google/models/text-embedding-005"
DEFAULT_EMBEDDING_REQUESTS_PER_MIN = 1000

# Corpus to GCS Bucket Mapping
CORPUS_TO_BUCKET_MAPPING = {
    "forest-policies": "usfs-forest-policies",
    "environmental-reports": "usfs-environmental-reports",
    "fire-management": "usfs-fire-management-docs",
}

# Account-specific settings
ORGANIZATION_DOMAIN = "usda.gov"
DEFAULT_CORPUS_NAME = "usfs-forest-service"
